source "https://github.com/CocoaPods/Specs.git"
platform :ios, "10.0"
use_frameworks!

target "WBProject" do
pod 'YYModel'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'BaiduMapKit'
end
